### ISSUE TITLE
Use of unicode in source file

### ISSUE THREAD

**Issue by TheArcaneBrony** [skyrina/hfksdjfskfhsjdfhkasfdhksf#1]
Using unicode in source files is bad practice. Consider using `\u1F97A` instead.
Not every system may be set up to support UTF-8.

**Comment by TheArcaneBrony** [comment]
This solution appears not to work.
Hereby, I propose a better, working solution:
`String.fromCodePoint(0x1F97A)`

**Comment by skyrina** [comment]
Thank you for bringing to our attention the issue of using unicode in source files. We appreciate your concern and take all feedback seriously.

After careful consideration, we have come to the conclusion that using unicode in source files is indeed not a best practice. Unicode characters can cause issues with compatibility and readability for other developers, as well as potentially causing conflicts with version control systems.

We are happy to inform you that we have addressed this issue in commit a7ed0dd and have ensured that all future code will adhere to this best practice. We apologize for any inconvenience this may have caused and are grateful for your assistance in helping us improve the quality of our code.
